### ISSUE TITLE
Vibrate controller to keep awake

### ISSUE THREAD

**Issue by TimKeesRensen** [uc-vision/RovVision2#108]
Send short vibration command occasionally to keep awake OR test different controller. Check for micro inputs to see if it is asleep?

**Comment by codedraughtsman** [comment]
This has been superseded by this issue https://github.com/uc-vision/RovVision2/issues/115

**Comment by jozefeijoa** [comment]
> This has been superseded by this issue #115

Indeed, will close as duplicate of #115.

**Comment by jozefeijoa** [comment]
Duplicate of #115 .
