### ISSUE TITLE
Add entry box to GUI for the user to input the Farm ID

### ISSUE THREAD

**Issue by codedraughtsman** [uc-vision/RovVision2#58]
Each backbone in Maclab's Able Tasman farm is labelled with a farm id (i.e. 168) 
Can we please add text entry box for us to be able to enter the farm id at the beginning of an automated scan?
This is then stored somewhere in the recorded files for us to use later in the dashboard.

It might also be a good idea to add a second entry box for the name of the company, in case we have two different companies' farms next to each other, making it very hard to tell them apart using GPS.

Quick note on GPS. The Able Tasman farm drifts quite a bit on the mooring, making GPS locations useful but hard to directly identity the backbone we are working on. Having the user enter the farm id is much more robust.

We could use a popup box for the user to enter the farm id and other details to avoid cluttering the GUI. We just need to get the user to do this while the ROV is on the surface. Otherwise they could drift into the lines while fulling out the farm id.

**Comment by orig74** [comment]
All added to dive form
