### ISSUE TITLE
Allow user to set automated scan mode via the D-pad on controller

### ISSUE THREAD

**Issue by codedraughtsman** [uc-vision/RovVision2#60]
Can we add the feature to be able to set the current automated scan mode state via the controller?

Thinking holding down one of the shoulder buttons and using the D-pad.

- up/down on the D-pad switches to go_up/go_down states
- left/right on the D-pad switches to slide right/left states.

Why this is useful
in the field, we sometimes try to start a scan in the middle or bottom of a line. This could be because we had to abort the scan or we were doing something else. Starting in the middle of the line and trying to scan upwards is not possible with the current automated scanning mode.

As for sliding from side to side, sometimes the rov switches to nearby line and it would be nice to just tell it to switch back to the old line. 

Currently we are taking manual control to do fix these issues and it would be very nice to be able to control the ROV at a higher level.

**Comment by TimKeesRensen** [comment]
Not needed
