### ISSUE TITLE
Publish and log internal dead reckoning data

### ISSUE THREAD

**Issue by codedraughtsman** [uc-vision/RovVision2#69]
Can we publish and log internal our dead reckoning data so we can correlate with our GPS positions when doing post-field trip analysis.

**Comment by orig74** [comment]
dead reckoning data is already published and logged (topic_pos_hold_pid_0, topic_pos_hold_pid_1) it is reliable as long as we didn't do DVL reset. In any case, we can post process the data to fine tune the position estimation based on DVL velocity data and IMU data which is also recorded.
