### ISSUE TITLE
GUI not setting D405 exposure on startup.

### ISSUE THREAD

**Issue by codedraughtsman** [uc-vision/RovVision2#70]
When starting up the GUI, the exposure setting for the D405 is not been used by the ROV/D405.

Steps:
- Set the D405 exposure setting in the GUI to 4.
- Restart the GUI
- The video coming back from the D405 shows footage which has the incorrect exposure setting.
- Changing  the exposure value in the GUI correctly changes the GUI.

My guess is that the GUI isn't sending the exposure setting to the D405 when it loads the settings from last session.

**Comment by orig74** [comment]
Hi this is definitely a bug. We currently don't have a process of sending current saved data on GUI side to the ROV on startup. I will fix that soon.

**Comment by orig74** [comment]
fixed
