### ISSUE TITLE
Create Log event using controller input

### ISSUE THREAD

**Issue by codedraughtsman** [uc-vision/RovVision2#71]
https://github.com/uc-vision/RovVision2/issues/65 is unclear if we can activate the log button using the Gamepad.

Can we have a way to create a Log event by pressing some key combo on the controller? Usually, the operator doesn't have enough time to click buttons on the GUI using the mouse.

**Comment by orig74** [comment]
Done

**Comment by codedraughtsman** [comment]
@orig74 What is the key combo to create a Log event?

**Comment by orig74** [comment]
It's not a key combo just a button named LOG

**Comment by codedraughtsman** [comment]
@orig74 Apologises, I see that the request was ambiguous.

It should be:
Can we have a way to create a Log event by pressing some key combo on the controller?

**Comment by codedraughtsman** [comment]
Have updated the title and description of this ticket, to be less ambiguous.

**Comment by orig74** [comment]
No need for special key combo. every time you presses a key (in recording state) in the game pad it is recorded so any unused combination I can detect and review in the log file. If possible use the the LOG button in the GUI since it will also include the text from the text box.

**Comment by codedraughtsman** [comment]
@orig74  I understand. 

Not sure how I feel about having any key combo be a stand in for a logged event. Would prefer a dedicated key combo, but this isn't important right now. Will invent a unused key combo for logging events.
