### ISSUE TITLE
Add a description box that allows us to describe what we are testing. 

### ISSUE THREAD

**Issue by codedraughtsman** [uc-vision/RovVision2#72]
Currently, we have no way of saving a message in the logged data which explains what we are currently testing.

This can result in us having difficulty finding test data relevant to a bug or issue.

Can we have a text box with a button that logs the text to the log file? This allows us a versatile way to annotate our data as we collect it.

Perhaps, this can extend [the LOG button?](https://github.com/uc-vision/RovVision2/issues/65)

Ideally we will use this to:
- mark what testing we are about to do/what testing we have ended.
- Annotate any bugs/issues we just observed
- location of farm
- weather conditions.
- issues that just happened in the last run.

**Comment by orig74** [comment]
Added dive form that will open before running the GUI.  This is a place to describe/add information regarding the dive before the dive.  In the future we can give it more structure such as combo boxes ,radio buttons etc. 

Also added a text box for free text to be saved any time you presses the log button.  You can use it to record events during the dive and to log events after the dive.
