### ISSUE TITLE
UE4bridge.py no such file or directory error

### ISSUE THREAD

**Issue by TaneRore** [uc-vision/RovVision2#73]
On surveyor branch, we are experiencing this issue while running run_sim.sh on two machines, Timothy Manning's Machine and my machine after fresh installation.

Timothy's Machine was not experiencing this issue until he pulled code Yesterday. 

![image](https://github.com/uc-vision/RovVision2/assets/95592598/a8bf968c-2d5e-4a90-994f-e21a49126157)

**Comment by orig74** [comment]
Hi,
Please run run_sim_pybullet.sh.
run_sim.sh is for unreal engine and it's currently not maintained.
Cheers,
Ori

**Comment by TaneRore** [comment]
Ah i see, got it, rookie error >_<

Cheers,
Rory
________________________________
