### ISSUE TITLE
Add functionality to scan same dropper line multiple times.

### ISSUE THREAD

**Issue by codedraughtsman** [uc-vision/RovVision2#75]
We are wanting to scan the same dropper line multiple times to test various things.

Can we have an automated way to scan the same dropper line multiple times?

One of the easiest ways would be to have a single line scan button.
Or we could have a "disable slide" checkbox, that prevents the ROV from sliding across to the next line. I'm a bit concerned that this could be left selected, causing issues with normal scans.

Would setting the slide value to 0 also work? Or would the ROV still move backwards

@TaneRore @orig74 What are your thoughts? It's going to be a pain to have to restart the automated scan. Especially since the ROV will only scan downwards when the scan is started.

**Comment by orig74** [comment]
Hi,
You can just set the horizontal_slide parameter to be zero and it would work. you can also change the minimal_step time to lower the time it stays in the slide state.
& It will go backwards but again you can set the back slide to 0.
