### ISSUE TITLE
Toggle button to turn off automatic detection

### ISSUE THREAD

**Issue by codedraughtsman** [uc-vision/RovVision2#81]
On the August field trip, we had issues with the automated scan incorrectly detecting the bottom of the dropper line, resulting in the ROV prematurely shifting to the next dropper line. We had to hack the code to disable the automatic detection part of the automated scan.

Can we please add an option to the GUI to enable/disable detection of the bottom of the dropper line.

**Comment by TimKeesRensen** [comment]
resolved by adding parameter for detect staret depth
