### ISSUE TITLE
Save the log file as a json file

### ISSUE THREAD

**Issue by codedraughtsman** [uc-vision/RovVision2#85]
Currently we are saving our log files as a pickle file. We want to be able to use grep and other tools to be able to search through all of the data we collect. In particular we want to identify logged events that are stored in the log files.

One solution is to save the log file as a Json file, which allows us to search it using normal text tools.
We can also run a script on the saved pickled file to create the json files as part of a post processing.

**Comment by orig74** [comment]
pickle files are binaries compressed and efficient. they also maintains the object type just as it was used in real-time. I am using the pickle files for analyzing the data and replaying it. 
I did create a script to scan multiple logs called scan_events_in_logs.py (in utils directory). It is possible to pipe the output to grep to get specific data. We can go ever it next week to see that it fits the purpose.
