### ISSUE TITLE
Skip stabilise mode when slide and backslide is set to zero

### ISSUE THREAD

**Issue by codedraughtsman** [uc-vision/RovVision2#87]
Currently when we try to scan a single dropper line multiple times, we set the slide and backslide to zero. This causes the ROV to skip the slide (and backslide) states. However the ROV still goes through two stabilise states. Can we clean this up so it will also skip the two stabilise states.

**Comment by TimKeesRensen** [comment]
Stabilise mode is needed, need to tune stabilise
